// eslint-disable-next-line import/prefer-default-export
export const problemConstants = {
  ADD_PROBLEM_START: 'ADD_PROBLEM_START',
  ADD_PROBLEM_SUCCESS: 'ADD_PROBLEM_SUCCESS',
  ADD_PROBLEM_FAIL: 'ADD_PROBLEM_FAIL',

  FETCH_PROBLEM_START: 'FETCH_PROBLEM_START',
  FETCH_PROBLEM_SUCCESS: 'FETCH_PROBLEM_SUCCESS',
  FETCH_PROBLEM_FAIL: 'FETCH_PROBLEM_FAIL',

  EDIT_PROBLEM_START: 'EDIT_PROBLEM_START',
  EDIT_PROBLEM_SUCCESS: 'EDIT_PROBLEM_SUCCESS',
  EDIT_PROBLEM_FAIL: 'EDIT_PROBLEM_FAIL',

  FETCH_LAST_SUBMISSION_START: 'FETCH_LAST_SUBMISSION_START',
  FETCH_LAST_SUBMISSION_SUCCESS: 'FETCH_LAST_SUBMISSION_SUCCESS',
  FETCH_LAST_SUBMISSION_FAIL: 'FETCH_LAST_SUBMISSION_FAIL',
};
