version: "3.8"

services:
    minio:
        image: quay.io/minio/minio:latest
        container_name: cpj-minio
        ports:
            - 8080:8080
            - 8081:8081
        volumes:
            - ~/minio/data:/data
        restart: unless-stopped
        environment:
            MINIO_ROOT_USER: cpj_minio
            MINIO_ROOT_PASSWORD: wp175wp175
        command: server /data --address ":8000" --console-address ":8081"
