version: "3.8"

services:
    judgecore:
        build:
            context: .
        container_name: cpj-judgecore
        restart: unless-stopped
        command: sh -c "cd /app/hack1 && yarn && cd .. && python -u main.py"
        ports:
            - 3000:3000
        env_file: 
            - .env
